export enum FieldType {
  "List" = "list",
  "BUTTON" = "Button",
  "FORM" = "Form",
  "MESSAGES" = "Messages",
  "PLACEHOLDER" = "Placeholder",
  "VALIDATION" = "Validation",
  "PARENT_MODULE" = "Parent Module",
  "MODULE" = "Module",
  "SUB_MODULE" = "Sub Module",
  "SYS_MSG" = "SYS_MSG",
  "OTHER" = "OTHER",
  "RADIO" = "Radio",
  "UNKNOWN" = "unknown",
}
